apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  labels:
    io.kompose.service: jaeger-tracing-frontend-service
  name: jaeger-tracing-frontend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jaeger-tracing-frontend-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      labels:
        io.kompose.service: jaeger-tracing-frontend-service
    spec:
      containers:
        - image: public.ecr.aws/j8e3t3x0/jaeger-tracing-frontend-service:0.0.6
          name: jaeger-tracing-frontend-service
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /app/.env.production
              name: frontend-env
              subPath: .env
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 3
          resources: {}
      restartPolicy: Always
      volumes:
        - name: frontend-env
          configMap:
            name: frontend-env

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-env
data:
  .env: |
     VUE_APP_NODEJS_SERVICE_URL=http://${API_BACKEND}:8081/
     VUE_APP_SERVER_PORT=8080